# Generated by Django 4.2.17 on 2024-12-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_posted",
            new_name="date",
        ),
    ]
